### ISSUE TITLE
Exercice 4 -> suivi

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/PROG_SLO1_24_25#7]
Exercice donnée le : 02.11.2023 => a réalisé comme préparatif pour le test de PROG 

ABR (@AlanBadertscher) =>NOT DONE 
NBN (@NicolasBessson) => NOT DONE 
ACL (@Sweedy3960) =>NOT DONE 
TCT (@Tass1l0) =>NOT DONE 
EDO (@etideoliveira)=>NOT DONE 
VCO (@kediven) =>NOT DONE 
KGR (@Kazanaris) =>NOT DONE 
JJE (@SwissMaverick) =>NOT DONE 
TMK (@ThomasMlynek) =>NOT DONE 
LPT (@luisalexanderP) =>NOT DONE 
MSI (@MatteoStefanelli) =>NOT DONE 
KSA (@Isand159) =>NOT DONE 
JBN (@blitshteynjacobES) =>NOT DONE

**Comment by Sweedy3960** [comment]
Ex4.c introuvable lien répertoire inexistant "K:\ES\Maitres-Eleves\SLO\Modules\SL121_LOGA\Exercices\fichiers_sources"

**Comment by PBYetml** [comment]
Merci pour le commentaire Aymeric (@Sweedy3960) -> MAJ dans 5min des sources dans la partie git + dans le one drive
